# homebrew
tap "homebrew/bundle"

# neovim and dependencies
brew "neovim"

brew "fzf"
brew "fd"
brew "prettier"
brew "ripgrep"
brew "stylua"

# tmux and dependencies
brew "tmux"

# core utilities
brew "coreutils"
brew "gnu-sed"
brew "ipcalc"
brew "jq"
brew "nmap"
brew "openssh"
brew "rclone"
brew "shellcheck"
brew "stow"
brew "telnet"
brew "tree"
brew "watch"

# git
brew "gh"
brew "git"
brew "lazygit"

# iterm2 and dependencies
cask "iterm2"

cask "font-meslo-lg-nerd-font"

# kubernetes
brew "k9s"
brew "kubectx"
brew "kubeseal"

# misc
cask "keepassxc"
cask "keystore-explorer"
cask "signal"
cask "wireshark"
