# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# index from 1
set -g base-index 1

# Splits
bind-key s switch-client -T plugin-split
bind-key -T plugin-split h split-window -v
bind-key -T plugin-split v split-window -h
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

# Mouse mode
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# DESIGN
# bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# copy mode
setw -g mode-style 'fg=#000000 bg=blue bold'

# panes
set -g pane-border-style 'fg=blue'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#000000 bg=blue bold'

set -g status-left '[#S] ' # session name
set -g status-left-length 20

set -g status-right '%H:%M %d-%m-%Y'
set -g status-right-length 50

setw -g window-status-current-style 'fg=red bg=green'
setw -g window-status-current-format ' #I #[fg=#000000]#W #[fg=yellow]#F '

setw -g window-status-style 'fg=red bg=blue'
setw -g window-status-format ' #I #[fg=#000000]#W #[fg=yellow]#F '

# messages
set -g message-style 'fg=#000000 bg=red bold'

# plugins
source-file -q ~/.tmux/plugins/init.conf

# window switcher
bind w display-popup -E "tmux list-windows -F '#I #W' | fzf --reverse | awk '{print \$1}' | xargs -I {} tmux select-window -t :{}"
